language: node_js

node_js: 16

branches:
  only:
  - source

before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install hexo-deployer-git --save
  - npm install hexo-generator-baidu-sitemap --save
  - wget https://github.com/jgm/pandoc/releases/download/2.11.2/pandoc-2.11.2-1-amd64.deb
  - sudo dpkg -i pandoc-2.11.2-1-amd64.deb
  - npm install hexo-renderer-pandoc --save

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "LENSHOOD"
  - git config user.email "lenshood.zxh@gmail.com"
  - sed -i "s/git_access_token/${GIT_ACCESS_TOKEN}/g" ./_config.yml
  - sed -i "s/gitee_access_token/${GITEE_ACCESS_TOKEN}/g" ./_config.yml
  - hexo deploy
