language: node_js

node_js: 13

branches:
  only:
  - source

before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install hexo-deployer-git --save
  - npm install hexo-generator-baidu-sitemap --save
  - npm uninstall hexo-renderer-marked
  - npm install hexo-renderer-pandoc --save

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "LENSHOOD"
  - git config user.email "zhangxh_job@sina.com"
  - sed -i "s/git_access_token/${GIT_ACCESS_TOKEN}/g" ./_config.yml
  - sed -i "s/gitee_access_token/${GITEE_ACCESS_TOKEN}/g" ./_config.yml
  - hexo deploy
